# Introduction to numpy Arrays

In [45]:
import numpy as np

In [46]:
#Single dimention numpy array
n1 = np.array([1,3,4,5,6])

In [47]:
n1

array([1, 3, 4, 5, 6])

In [48]:
type(n1)

numpy.ndarray

In [49]:
#multi Dimention numpy array
n2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [50]:
n2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
type(n2)

numpy.ndarray

In [52]:
#initializing numpy array with zero
import numpy as np
n3 = np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
n4 = np.zeros((6,6))
n4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [54]:
#initializing numpy array with same numbers
import numpy as np
n1 = np.full((2,2), 10)
n1

array([[10, 10],
       [10, 10]])

In [55]:
n5 = np.full((3,3), (5))

In [56]:
n5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [57]:
n6 = np.full((3,6), 9)

In [58]:
n6

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [59]:
#initializing numpy array within a range

In [60]:
import numpy as np
n1 = np.arange(10,20) #starting -> ending
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
import numpy as np
n1 = np.arange(1,105,10) #starting-> ending-> skepping
n1

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101])

In [62]:
#initializing numpy array with random numbers
import numpy as np
n1 = np.random.randint(1,100,5) #starting -> ending -> random numbers
n1

array([87, 30, 12, 68, 80])

In [63]:
#checking the shape of numpy arrays

In [64]:
import numpy as np
n1 = np.array([[1,2,3], [4,5,6]])
n1.shape

(2, 3)

In [65]:
n1.shape = (3,2)
n1.shape

(3, 2)

In [66]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

# Joining NumPy Arrays.


In [72]:
# 3 stacking operation of numpy library
# 1.vstack() 2.hstack() 3.colunmn_stack()

In [69]:
import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [70]:
import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [71]:
import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# Numpy Intersection & Difference


In [77]:
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

In [78]:
np.intersect1d(n1,n2)

array([50, 60])

In [79]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [80]:
np.intersect1d(n2,n1)

array([50, 60])

# Numpy Array Mathematics


In [81]:
#Addition of numpy arrays

In [82]:
import numpy as np
n1 = np.array([10,20])
n2 = np.array([30,40])
np.sum((n1,n2))

100

In [83]:
np.sum([n1,n2], axis = 0)

array([40, 60])

In [84]:
np.sum([n1,n2], axis = 1)

array([30, 70])

# Numpy array Mathematics

In [86]:
#Addition
import numpy as np
n1 = np.array([10,20,30])
n1 = n1+1
n1

array([11, 21, 31])

In [88]:
#Substraction
import numpy as np
n1 = np.array([10,20,30])
n1 = n1-1
n1

array([ 9, 19, 29])

In [89]:
#Multiplication
import numpy as np
n1 = np.array([10,20,30])
n1 = n1*2
n1

array([20, 40, 60])

In [90]:
#Division
import numpy as np
n1 = np.array([10,20,30])
n1 = n1/2
n1

array([ 5., 10., 15.])

# Numpy Math Function

In [92]:
#Mean
import numpy as np
n1 = np.array([10,20,30,40,50,60])
np.mean(n1)

35.0

In [93]:
#Standard Deviation
import numpy as np
n1 = np.array([10,20,30,40,50,60])
np.std(n1)

17.07825127659933

In [94]:
#Median
import numpy as np
n1 = np.array([10,20,30,40,50,60])
np.median(n1)

35.0

# Saving and Loading Numpy Array


In [96]:
#Saving Numpy Array
import numpy as np
n1 = np.array([10,20,30,40,50,60])
np.save('my_numpy',n1)

In [98]:
#Loading Numpy Array
np.load('my_numpy.npy')

array([10, 20, 30, 40, 50, 60])

# Intro to Pandas


In [99]:
#Pandas stands for panel data and is the core library for data manipulation and data analysis
#Single-dimentional -> Series Object
#Multi-dimentional - > Data-Frame

# Pandas Series Object


In [101]:
#Series Object is one-dimentional labeled array

In [102]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [103]:
type(s1)

pandas.core.series.Series

In [104]:
#Changing Index

In [105]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [109]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
#numbers -> Changing index (0,1,2,3,4) to (a,b,c,d,e)
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [110]:
#Series object from dictonary

In [112]:
import pandas as pd
pd.Series({'a':10,'b':20,'c':30})

a    10
b    20
c    30
dtype: int64

In [113]:
#Changing Index Position

In [114]:
import pandas as pd
pd.Series({'a':10,'b':20,'c':30}, index=['b','c','d','a'])

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64

In [115]:
#Extracting Individual Elements

In [116]:
#Extracting a Single element
import pandas as pd
s1 = pd.Series([1,2,3,4,5,6,7,8,9])
s1[3] #single element

4

In [119]:
#Extracting elements from back
s1 = pd.Series([1,2,3,4,5,6,7,8,9])
s1[-3:] #last 3 elements

6    7
7    8
8    9
dtype: int64

In [120]:
#Extracting a sequence of elements
s1 = pd.Series([1,2,3,4,5,6,7,8,9])
s1[:4] #sequence elements

0    1
1    2
2    3
3    4
dtype: int64

In [121]:
#Basic Math Operation on series

In [122]:
#Adding a scalar values to Series Elements
s1 +5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int64

In [123]:
s1 = pd.Series([1,2,3,4,5,6,7,8,9])
s2 = pd.Series([10,20,30,40,50,60,70,80,90])

In [124]:
s1+s2

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

In [128]:
s1,s2 #Print s1 and s2

(0    1
 1    2
 2    3
 3    4
 4    5
 5    6
 6    7
 7    8
 8    9
 dtype: int64,
 0    10
 1    20
 2    30
 3    40
 4    50
 5    60
 6    70
 7    80
 8    90
 dtype: int64)

In [127]:
s1+s2 #Adding 2 sub elements

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

# Intro to Pandas Dataframe


In [129]:
#DataFrame is a 2-dimentional labelled data-structure

In [130]:
#Creating a Dataframe

In [136]:
import pandas as pd
df1 = pd.DataFrame({"Name":['Ashik', 'Nishat', 'Arafat', 'Afrin', 'Nazneen', 'Iqra', 'Soma', 'Maruf', 'Nayeem'], "Marks":[50,90,92,94,39,56,88,98,43], "Subject":['Algorithm', 'DataBase', 'Math', 'Economics', 'Digital logic', 'Python', 'C++', 'Java', 'C']})
df1


Name  Marks        Subject
0    Ashik     50      Algorithm
1   Nishat     90       DataBase
2   Arafat     92           Math
3    Afrin     94      Economics
4  Nazneen     39  Digital logic
5     Iqra     56         Python
6     Soma     88            C++
7    Maruf     98           Java
8   Nayeem     43              C

In [137]:
#Dataframe In-Built Function
# 1.head()  2.shape()  3.describe()  4.tail()

In [140]:
iris=pd.read_csv('iris.csv')


In [141]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [142]:
iris.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [144]:
iris.shape #row -> column

(150, 5)

In [145]:
iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [148]:
#iloc[]

#.iloc would help us to extract rows and column with respect to their index
iris.iloc[0:3,0:2] # row (0 to 3 row) -> column (0 to 2 columns)

Sepal.Length  Sepal.Width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2

In [147]:
iris.iloc[0:10,0:5]

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [155]:
iris.loc[5:11,('Sepal.Length','Species')]

Sepal.Length Species
5            5.4  setosa
6            4.6  setosa
7            5.0  setosa
8            4.4  setosa
9            4.9  setosa
10           5.4  setosa
11           4.8  setosa

In [156]:
#Drpping Columns

In [157]:
iris.drop('Sepal.Length', axis = 1)

Sepal.Width  Petal.Length  Petal.Width    Species
0            3.5           1.4          0.2     setosa
1            3.0           1.4          0.2     setosa
2            3.2           1.3          0.2     setosa
3            3.1           1.5          0.2     setosa
4            3.6           1.4          0.2     setosa
..           ...           ...          ...        ...
145          3.0           5.2          2.3  virginica
146          2.5           5.0          1.9  virginica
147          3.0           5.2          2.0  virginica
148          3.4           5.4          2.3  virginica
149          3.0           5.1          1.8  virginica

[150 rows x 4 columns]

In [158]:
#Dropping Rows

In [160]:
iris.drop([1,2,3], axis = 0)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

# Pandas Functions


In [161]:
iris.mean()

C:\Users\devsm\AppData\Local\Temp\ipykernel_7884\935066809.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris.mean()


Sepal.Length    5.843333
Sepal.Width     3.057333
Petal.Length    3.758000
Petal.Width     1.199333
dtype: float64

In [162]:
iris.median()

C:\Users\devsm\AppData\Local\Temp\ipykernel_7884\1297003277.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  iris.median()


Sepal.Length    5.80
Sepal.Width     3.00
Petal.Length    4.35
Petal.Width     1.30
dtype: float64

In [163]:
iris.min()

Sepal.Length       4.3
Sepal.Width        2.0
Petal.Length       1.0
Petal.Width        0.1
Species         setosa
dtype: object

In [164]:
iris.max()

Sepal.Length          7.9
Sepal.Width           4.4
Petal.Length          6.9
Petal.Width           2.5
Species         virginica
dtype: object

In [165]:
#More Pandas Function

In [166]:
def half(s):
    return s*0.5

In [169]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [170]:
def double_make(s):
    return s*2

In [173]:
iris[['Sepal.Width','Petal.Width']].apply(double_make)

Sepal.Width  Petal.Width
0            7.0          0.4
1            6.0          0.4
2            6.4          0.4
3            6.2          0.4
4            7.2          0.4
..           ...          ...
145          6.0          4.6
146          5.0          3.8
147          6.0          4.0
148          6.8          4.6
149          6.0          3.6

[150 rows x 2 columns]

In [174]:
#value Count

In [175]:
iris['Species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: Species, dtype: int64

In [176]:
#sort_values()

In [177]:
iris.sort_values(by='Sepal.Length')

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [178]:
iris['Species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: Species, dtype: int64